### ISSUE TITLE
Performance Characteristics

### ISSUE THREAD

**Issue by mickeyl** [Flight-School/MessagePack#15]
Mattt, thanks for this great library!

In order to decide on my next on-disk serialization format I did some benchmarks, in particular I compared `MessagePack` against Foundation's `PropertyListEncoder`.

`MessagePack` creates serialized results that are about 40% smaller than the `PropertyListEncoder`, however it took about 300% of encoding time in contrast to `PropertyListEncoder`.

I wonder where this difference comes from – naively, I had expected somewhat of a linearity between size of the result and encoding time. I did not profile yet, do you have any idea whether integrating a C-based `msgpack` encoder could perhaps improve the runtime?

**Comment by lmcd** [comment]
Also wondering why 3rd party binary encoder/decoders perform so terribly vs `JSONEncoder`/`PropertyListEncoder`...

**Comment by mattt** [comment]
Apologies for not responding sooner, @mickeyl.

This library was developed as a supplemental resource for [Flight School Guide to Swift Codable](https://flight.school/books/codable), so the primary goal was comprehensibility rather than performance. I'm sure there are some trivial performance optimizations that could bring this to closer to the built-in Foundation decoders, but I haven't looked into that.

If your needs are performance-sensitive, I'd recommend skipping `Codable` entirely and initializing as directly as possible from the `msgpack` C library. For information about why `Codable` isn't as fast as it could be, see [this thread from the Swift forums](https://forums.swift.org/t/rearchitecting-jsonencoder-to-be-much-faster/28139).

**Comment by mickeyl** [comment]
I see, makes sense. In the meantime, I settled on https://github.com/hirotakan/MessagePacker, i agree that Codable itself accounts for a major part of the general slowness. Let's hope that the new serialization discussion leads to anything soon.
